### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by dprada** [sat28/githubcommit#1]
Hi!

I came across your comment in https://github.com/Lab41/sunny-side-up/issues/78#issuecomment-357621792 and I am pretty excited about the possibility of using your extension. I was really craving for something to push/pull changes straight from the Jupyter Notebooks in JupyterHub to/from Github.

Is your extension the only way to do it?

We will give you feedback on our experience.
Great effort.
Thanks

**Comment by sat28** [comment]
Thanks @dprada, looking forward to your response.
