### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Jearny58** [sat28/githubcommit#11]
Hello, I was trying to install the extension and when I entered in the (jupyter nbextension install --py githubcommit) command in the terminal (FYI using a Mac) I got the following error:

"PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'"

I'm still relatively new to Github and Jupyter so I'm a little lost on how to fix this. Any help would be greatly appreciated!

Thanks!

**Comment by sat28** [comment]
Try executing the command sudo chmod 777 /usr/local/share/jupyter
