### ISSUE TITLE
Windows 10 how to ?

### ISSUE THREAD

**Issue by runsun-edu** [sat28/githubcommit#15]
Is this program working only on Linux? 

It seems not possible to run `source ~/githubcommit/env.sh` under Windows 10. 

I tried `git bash`, `Windows Linux Subsystem`, `Cygwin` ... they all can run that line, but all set the env. vars in a linux environment that the later `handles.py` can't access.

**Comment by sat28** [comment]
There is no source command in windows so it won't work. I have not tried it over a Windows system as of now. When trying from cygwin, jupyter should be run from within cygwin only.

**Comment by runsun-edu** [comment]
yea that's what I figure. Have to replace `env.sh` with a `~.json` file and use python to read it.
