### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by nikolayvoronchikhin** [sat28/githubcommit#6]
Hi, I have a few doubts. 

1. Does this extension work with JupyterHub? If yes, do I need to add any extra setting to jupyterhub_config.py?

2. Does this extension work with GitHub Enterprise (or only the public GitHub)? 
If yes, what additional settings are required in my ~/githubcommit/env.sh to connect my JupyterHub user to GitHub Enterprise? 

I have set the settings to env.sh as in your example, but when I click on Commit and Push Notebook, I don't get any output and I don't see the notebook in my GitHub Enterprise repo either.

**Comment by Dimpison** [comment]
the same problem, but using public GitHub
works in jupyter on VM, but not working into JupyterHub into kubernetes
@nikolayvoronchikhin do you found the solution?
(cc: @sat28)

**Comment by nikolayvoronchikhin** [comment]
@Dimpison No, we did not find solution for this, still waiting for response.

**Comment by sat28** [comment]
@kannankumar for GitHub Enterprise you will have to make a tunnel to your Github and then change the env.sh with the URL of your GitHub. I have also used it along with JupyterHub through DockerSpawner.
