### ISSUE TITLE
Clarify the readme

### ISSUE THREAD

**Issue by amaa15** [sat28/githubcommit#7]
Would you please explain more about the following points:

- Run the command - source ~/githubcommit/env.sh
from where to run it?
- Configure ssh key (present in ~/.ssh/id_rsa.pub or specified location) in github account 
How to configure?

**Comment by amaa15** [comment]
I have received errors, the last one is 404 File not found when I press the commit button.

I really, Appreciate the work you did, and I am eager to test it and work with it.

**Comment by sat28** [comment]
@radocisar provides the correct explanation. I will also update the README.md
