### ISSUE TITLE
not getting git icon on jup notebook

### ISSUE THREAD

**Issue by ishaq4466** [sat28/githubcommit#8]
i have did all the steps for installing and set the id_rsa.pub in my git account.
but when i run the jupyter notebook i didnt see any of the git icon for commiting and pushing
btw im hosting my notebook on aws ec2 ubuntu instance
plz helppppppp

![image](https://user-images.githubusercontent.com/34211135/44484294-06c3b200-a66b-11e8-92b9-ec15a6490f23.png)

**Comment by Brensley** [comment]
Ishaq4466, check to see where your Anaconda is installed. I was able to make this work on Windows and also RHEL 7. Make sure your Anaconda is installed in ROOT. If its installed on /OPT then I know for a fact it wouldn't work. Let me know of that works for you. Please update this post when done. Thanks again .

**Comment by sat28** [comment]
@ishaq4466 please make sure the extension is enabled by running the commands -
```
jupyter serverextension enable --py githubcommit
jupyter nbextension install --py githubcommit
```
The resultant of these command will be validating - Ok
